//Моковые фильтры
export const filterList = [
  { name: "All", type: "all" },
  { name: "Marketing", type: "marketing" },
  { name: "Management", type: "management" },
  { name: "HR & Recruting", type: "recruiting" },
  { name: "Design", type: "design" },
  { name: "Development", type: "development" },
];

//Моковые карточки
export const cardList = [
  {
    id: 1,
    type: "marketing",
    tag: "Marketing",
    title: "The Ultimate Google Ads Training Course",
    price: "100",
    lecturer: "Jerome Bell",
    image: "Jerome Bell.png",
  },
  {
    id: 2,
    type: "management",
    tag: "Management",
    title: "Prduct Management Fundamentals",
    price: "480",
    lecturer: "Marvin McKinney",
    image: "Marvin McKinney.png",
  },
  {
    id: 3,
    type: "recruiting",
    tag: "HR & Recruting",
    title: "HR  Management and Analytics",
    price: "200",
    lecturer: "Leslie Alexander Li",
    image: "Leslie Alexander Li.png",
  },
  {
    id: 4,
    type: "marketing",
    tag: "Marketing",
    title: "Brand Management & PR Communications",
    price: "530",
    lecturer: "Kristin Watson",
    image: "Kristin Watson.png",
  },
  {
    id: 5,
    type: "design",
    tag: "Design",
    title: "Graphic Design Basic",
    price: "500",
    lecturer: "Guy Hawkins",
    image: "Guy Hawkins.png",
  },
  {
    id: 6,
    type: "management",
    tag: "Management",
    title: "Business Development Management",
    price: "400",
    lecturer: "Dianne Russell",
    image: "Dianne Russell.png",
  },
  {
    id: 7,
    type: "development",
    tag: "Development",
    title: "Highload Software Architecture",
    price: "600",
    lecturer: "Brooklyn Simmons",
    image: "Brooklyn Simmons.png",
  },
  {
    id: 8,
    type: "recruiting",
    tag: "HR & Recruting",
    title: "Human Resources – Selection and Recruitment",
    price: "150",
    lecturer: "Kathryn Murphy",
    image: "Kathryn Murphy.png",
  },
  {
    id: 9,
    type: "design",
    tag: "Design",
    title: "User Experience. Human-centered Design",
    price: "250",
    lecturer: "Cody Fisher",
    image: "Cody Fisher.png",
  },
];
